import Head from "next/head"
import Header from "../header/Header"
import useAuth from "../../hooks/useAuth"
import { use, useEffect } from "react"
import { ChildrenProps } from "../../helpers/interfaces"

const Layout = ({ children }: ChildrenProps): JSX.Element => {
  const { loading } = useAuth()
  return (
    <>
      <Head>
        <title>School Adm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading ? (
        <p>loading...</p>
      ) : (
        <>
          <Header />
          <main className="pt-6">{children}</main>
        </>
      )}
    </>
  )
}

export default Layout
