import Head from 'next/head'
import Header from '../header/Header'
import useAuth from '../../hooks/useAuth'
import { use, useEffect } from 'react'

const Layout = ({children}:any) => {
  const {loading} = useAuth()
  return (
    <>
        <Head>
            <title>School Adm</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {loading ? <p>loading...</p> :
        <>
          <Header />
          <main>
              {children}
          </main>
        </>}
    </>
  )
}

export default Layout